### ISSUE TITLE
Code review - Vortex Labs

### ISSUE THREAD

**Issue by leoarmelin** [JohannesAlves/cats#1]
Thanks for the submission, and great work! Here are some feedback regarding the code:

## /src/api/index.tsx

Never let the api key be accessible publicly, even if it's a free one. Use .env variables instead.

## /src/utils/capitalizeFirstLetter.ts

It's not a good practice to call a variable `string` or any other primitive types.

## /src/components/Card/index.tsx

You used NextJS `Image` with `fill` but didn't added `sizes` properly. You can reduce the images loading time with this property! [DOCS](https://nextjs.org/docs/app/api-reference/components/image#sizes)

## General

I've never seen the way you call views/models. It seems very good for simple projects like this one, and it's better to use other strategies for bigger projects.

Fetching data inside components is not a good idea. In many cases, frontend has a single source of truth, usually a repository/domain/model/context. One example is having to mock the api call instead of just mocking the components parameters, like you did in `CategorieButtons` component.

**Comment by JohannesAlves** [comment]
Excelent points in your code review Leoar! Thank's so much.

**Comment by JohannesAlves** [comment]
https://github.com/JohannesAlves/cats/pull/2 My pull request just for fun.
